### ISSUE TITLE
Add a help command to improve user guidance

### ISSUE THREAD

**Issue by AmalChandru** [AmalChandru/metrics-monkey#3]
Implement a help command that provides users with information about available commands, their usage, and any relevant options. This will enhance the user experience and make our tool more accessible to new users.

**Comment by AmalChandru** [comment]
Hey @abhishekpaturkar assigning this to you

**Comment by abhishekpaturkar** [comment]
Please check PR.

**Comment by AmalChandru** [comment]
Thanks for the PR. I have suggested some changes there itself.

**Comment by abhishekpaturkar** [comment]
Done with formatting and updated README.md
